# @package _global_
defaults:
  - /trainer: default
  - /loader: default
  - /dataset: ss
  - /task: multiclass_classification
  - /optimizer: adamw
  - /scheduler: cosine
  - /callbacks: [base, checkpoint]

train:
  monitor: val/accuracy # Needed for plateau scheduler
  mode: max

encoder: null

# we need this for classification!
decoder:
  _name_: token

wandb:
  project: ss