model:
  _name_: lm
  d_model: 256
  n_layer: 8
  d_inner: 1024  # ${eval:4 * ${.d_model}}
  vocab_size: 12
  resid_dropout: 0.0
  embed_dropout: 0.1
  fused_mlp: False # figure out how to use fused MLP, maybe only with bf16 + a100
  fused_dropout_add_ln: False
  residual_in_fp32: True
  pad_vocab_size_multiple: 8
  return_hidden_state: True  # in 2nd position of output tuple (1st is logits)
  checkpoint_mixer: False
  checkpoint_mlp: False
  layer:
    _name_: hyena
    emb_dim: 5
    filter_order: 64
    local_order: 3
    l_max: 160_002  # add 2 for ckpt
    modulate: True
    w: 10
    lr: 6e-4
    wd: 0.0
    lr_pos_emb: 0.0

tuning:
  tuning_samples:
    - 2
    - 16
    - 64
    - 256
  batch_size: 2 # for tuning
  max_epochs: 1
  lr: 1e-4
  weight_decay: 0
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  # ema_decay: 0.98

dataset:
  tokenizer_name: char
  batch_size: 4 # used for data loading & evaluation
  rc_aug: False
  shots:
    - 0
    - 2
    - 16
    - 32
  num_workers: 10

seed: 12345