model:
  _name_: dna_embedding
  d_model: 256
  n_layer: 2
  d_inner: ${eval:4 * ${.d_model}}
  vocab_size: 32
  resid_dropout: 0.0
  embed_dropout: 0.1
  attn_layer_idx: [0, 1]  # if passing these attn flags, then MHA auto used
  attn_cfg:
    num_heads: 8
    use_flash_attn: true  # figure out how to use
    fused_bias_fc: false  # this doesn't work for some reason, loss not going down
    dropout: 0.1
  fused_mlp: false # figure out how to use fused MLP, maybe only with bf16 + a100
  fused_dropout_add_ln: true
  residual_in_fp32: true
  pad_vocab_size_multiple: 8

train:
  d_output: 24

dataset:
  dataset_name: location # human_enhancers_cohn
  dest_path: /raid_elmo/home/lr/zym/data/protein_data/fine_tuning/localization
  max_length: 1024
  d_output: 24  # num classes
  train_len: 9977
  num_workers: 4
  tokenizer_name: char
  batch_size: 128  # Per GPU