model:
  _name_: lm
  d_model: 256
  n_layer: 8
  d_inner: 1024  # ${eval:4 * ${.d_model}}
  vocab_size: 12
  resid_dropout: 0.0
  embed_dropout: 0.1
  fused_mlp: False # figure out how to use fused MLP, maybe only with bf16 + a100
  fused_dropout_add_ln: False
  residual_in_fp32: True
  pad_vocab_size_multiple: 8
  return_hidden_state: True  # in 2nd position of output tuple (1st is logits)
  checkpoint_mixer: False
  checkpoint_mlp: False
  layer:
    _name_: hyena
    emb_dim: 5
    filter_order: 64
    local_order: 3
    l_max: 160_002  # add 2 for ckpt
    modulate: True
    w: 10
    lr: 6e-4
    wd: 0.0
    lr_pos_emb: 0.0

tuning:
  soft_tokens:
    - 0
    - 2
    - 32
    - 128
    - 512
    - 2048
    - 8192
    - 32768
  soft_token_pdrop: 0.1 # dropout probability for soft tokens
  max_epochs: 20
  lr: 1e-3
  weight_decay: 0.
  gradient_clip_val: 1.0
  accumulate_grad_batches: 8 # number of batches to accumulate before gradient update
  ema_decay: 0.9 # decay rate for updates of expected moving average of trained models

dataset:
  tokenizer_name: char
  batch_size: 2
  rc_aug: True # no augmentation
  shots:
    # - 0
    - 2
    - 32
    - 128
  num_workers: 10

seed: 12345