model:
  _name_: dna_embedding
  d_model: 256
  n_layer: 2
  d_inner: 1024
  vocab_size: 32
  resid_dropout: 0.0
  embed_dropout: 0.1
  fused_mlp: False # figure out how to use fused MLP, maybe only with bf16 + a100
  fused_dropout_add_ln: false       
  checkpoint_mixer: false  # set true for memory reduction
  checkpoint_mlp: false  # set true for memory reduction                                                                                                       
  residual_in_fp32: True
  pad_vocab_size_multiple: 8
  layer:
    _name_: hyena
    emb_dim: 5
    filter_order: 64
    short_filter_order: 3
    l_max: 1026  # required to be set the same as the pretrained model if using, don't forget the +2!  ${eval:${dataset.max_length}+2}
    modulate: True
    w: 10
    lr: 6e-4
    wd: 0.0
    lr_pos_emb: 0.0


train:
  d_output: 24

dataset:
  dataset_name: stability # human_enhancers_cohn
  dest_path: /raid_elmo/home/lr/zym/data/protein_data/fine_tuning/stability
  max_length: 1024
  d_output: 1  # num classes
  train_len: 53614
  num_workers: 4
  tokenizer_name: char
  batch_size: 128  # Per GPU