_name_: prot14m
# fasta_file: '/home/lr/zym/research/data/protein_data/Pfam-A_small_new.fasta'
fasta_file: '/raid_elmo/home/lr/zym/data/protein_data/Pfam-A-new.fasta'
prot14m_dir: '/raid_elmo/home/lr/zym/data/protein'
dataset_name: prot14m
tokenizer_name: null
cache_dir: null
max_length: 512
add_eos: True
batch_size: 8  # per GPU
batch_size_eval: ${eval:${.batch_size} * 1}
num_workers: 4  # For preprocessing only
shuffle: True
pin_memory: True
__train_len: ${div_up:1_000_000_000, ${.max_length}}
__l_max: ${.max_length}