_name_: rna32m
bed_file: null
# fasta_file: '/raid_elmo/home/lr/zym/data/rna_data/rnacentral_active.fasta'
fasta_file: '/home/lr/zym/research/data/rna_datarnacentral.fasta'
rna32m_dir: '/raid_elmo/home/lr/zym/data/rna_data'
dataset_name: rna32m
tokenizer_name: null
cache_dir: null
max_length: 1024
add_eos: True
batch_size: 8  # per GPU
batch_size_eval: ${eval:${.batch_size} * 2}
num_workers: 4  # For preprocessing only
shuffle: True
pin_memory: True
__train_len: ${div_up:1_000_000_000, ${.max_length}}
__l_max: ${.max_length}