_name_: ss
dataset_name: ss
max_length: 512
dest_path: /raid_elmo/home/lr/zym/data/protein_data/fine_tuning/secondary_structure
tokenizer_name: char
cache_dir: null
add_eos: False
batch_size: 128 # per GPU
batch_size_eval: 1
num_workers: 4  # For preprocessing only
shuffle: True
pin_memory: True
train_len: 8678
__l_max: ${.max_length}
use_padding: True
padding_side: 'left'
rc_aug: False